language: python
cache: pip

branches:
  only:
    - master

env:
  global:
    - DJANGO_SETTINGS_MODULE=tests.settings

templates:
  django111: &django111 DJANGO_VERSION=1.11.*
  django20: &django20 DJANGO_VERSION=2.0.*
  django21: &django21 DJANGO_VERSION=2.1.*
  django22: &django22 DJANGO_VERSION=2.2.*
  django30: &django30 DJANGO_VERSION=3.0.*
  django31: &django31 DJANGO_VERSION=3.1.*
  djangomaster: &djangomaster DJANGO_VERSION=master

  postgres: &postgres DATABASE_URL=postgres://postgres@/django_relativity
  mysql: &mysql DATABASE_URL=mysql://root:@localhost/django_relativity
  sqlite: &sqlite  DATABASE_URL=sqlite://

  pgdb: &pgdb
    addons: {postgresql: "10"}
  mariadb: &mariadb
    addons: {mariadb: "10.3"}


matrix:
  fast_finish: true
  include:
    - { python: pypy, env: [*django111, *postgres], <<: *pgdb}
    - { python: pypy, env: [*django111, *mysql], <<: *mariadb}
    - { python: pypy, env: [*django111, *sqlite]}

    - { python: pypy3, env: [*django111, *postgres], <<: *pgdb}
    - { python: pypy3, env: [*django111, *mysql], <<: *mariadb}
    - { python: pypy3, env: [*django111, *sqlite]}
    - { python: pypy3, env: [*django20, *postgres], <<: *pgdb}
    - { python: pypy3, env: [*django20, *mysql], <<: *mariadb}
    - { python: pypy3, env: [*django20, *sqlite]}
    - { python: pypy3, env: [*django21, *postgres], <<: *pgdb}
    - { python: pypy3, env: [*django21, *mysql], <<: *mariadb}
    - { python: pypy3, env: [*django21, *sqlite]}
    - { python: pypy3, env: [*django22, *postgres], <<: *pgdb}
    - { python: pypy3, env: [*django22, *mysql], <<: *mariadb}
    - { python: pypy3, env: [*django22, *sqlite]}
    - { python: pypy3, env: [*django30, *postgres], <<: *pgdb}
    - { python: pypy3, env: [*django30, *mysql], <<: *mariadb}
    - { python: pypy3, env: [*django30, *sqlite]}
    - { python: pypy3, env: [*django31, *postgres], <<: *pgdb}
    - { python: pypy3, env: [*django31, *mysql], <<: *mariadb}
    - { python: pypy3, env: [*django31, *sqlite]}
    - { python: pypy3, env: [*djangomaster, *postgres], <<: *pgdb}
    - { python: pypy3, env: [*djangomaster, *mysql], <<: *mariadb}
    - { python: pypy3, env: [*djangomaster, *sqlite]}

    - { python: 2.7, env: [*django111, *postgres], <<: *pgdb}
    - { python: 2.7, env: [*django111, *mysql], <<: *mariadb}
    - { python: 2.7, env: [*django111, *sqlite]}

    - { python: 3.4, env: [*django111, *postgres], <<: *pgdb}
    - { python: 3.4, env: [*django111, *sqlite]}
    - { python: 3.4, env: [*django20, *postgres], <<: *pgdb}
    - { python: 3.4, env: [*django20, *sqlite]}

    - { python: 3.5, env: [*django111, *postgres], <<: *pgdb}
    - { python: 3.5, env: [*django111, *mysql], <<: *mariadb}
    - { python: 3.5, env: [*django111, *sqlite]}
    - { python: 3.5, env: [*django20, *postgres], <<: *pgdb}
    - { python: 3.5, env: [*django20, *mysql], <<: *mariadb}
    - { python: 3.5, env: [*django20, *sqlite]}
    - { python: 3.5, env: [*django21, *postgres], <<: *pgdb}
    - { python: 3.5, env: [*django21, *mysql], <<: *mariadb}
    - { python: 3.5, env: [*django21, *sqlite]}
    - { python: 3.5, env: [*django22, *postgres], <<: *pgdb}
    - { python: 3.5, env: [*django22, *mysql], <<: *mariadb}
    - { python: 3.5, env: [*django22, *sqlite]}

    - { python: 3.6, env: [*django111, *postgres], <<: *pgdb}
    - { python: 3.6, env: [*django111, *mysql], <<: *mariadb}
    - { python: 3.6, env: [*django111, *sqlite]}
    - { python: 3.6, env: [*django20, *postgres], <<: *pgdb}
    - { python: 3.6, env: [*django20, *mysql], <<: *mariadb}
    - { python: 3.6, env: [*django20, *sqlite]}
    - { python: 3.6, env: [*django21, *postgres], <<: *pgdb}
    - { python: 3.6, env: [*django21, *mysql], <<: *mariadb}
    - { python: 3.6, env: [*django21, *sqlite]}
    - { python: 3.6, env: [*django22, *postgres], <<: *pgdb}
    - { python: 3.6, env: [*django22, *mysql], <<: *mariadb}
    - { python: 3.6, env: [*django22, *sqlite]}
    - { python: 3.6, env: [*django30, *postgres], <<: *pgdb}
    - { python: 3.6, env: [*django30, *mysql], <<: *mariadb}
    - { python: 3.6, env: [*django30, *sqlite]}
    - { python: 3.6, env: [*django31, *postgres], <<: *pgdb}
    - { python: 3.6, env: [*django31, *mysql], <<: *mariadb}
    - { python: 3.6, env: [*django31, *sqlite]}
    - { python: 3.6, env: [*djangomaster, *postgres], <<: *pgdb}
    - { python: 3.6, env: [*djangomaster, *mysql], <<: *mariadb}
    - { python: 3.6, env: [*djangomaster, *sqlite]}

    - { python: 3.7, env: [*django111, *postgres], <<: *pgdb}
    - { python: 3.7, env: [*django111, *mysql], <<: *mariadb}
    - { python: 3.7, env: [*django111, *sqlite]}
    - { python: 3.7, env: [*django20, *postgres], <<: *pgdb}
    - { python: 3.7, env: [*django20, *mysql], <<: *mariadb}
    - { python: 3.7, env: [*django20, *sqlite]}
    - { python: 3.7, env: [*django21, *postgres], <<: *pgdb}
    - { python: 3.7, env: [*django21, *mysql], <<: *mariadb}
    - { python: 3.7, env: [*django21, *sqlite]}
    - { python: 3.7, env: [*django22, *postgres], <<: *pgdb}
    - { python: 3.7, env: [*django22, *mysql], <<: *mariadb}
    - { python: 3.7, env: [*django22, *sqlite]}
    - { python: 3.7, env: [*django30, *postgres], <<: *pgdb}
    - { python: 3.7, env: [*django30, *mysql], <<: *mariadb}
    - { python: 3.7, env: [*django30, *sqlite]}
    - { python: 3.7, env: [*django31, *postgres], <<: *pgdb}
    - { python: 3.7, env: [*django31, *mysql], <<: *mariadb}
    - { python: 3.7, env: [*django31, *sqlite]}
    - { python: 3.7, env: [*djangomaster, *postgres], <<: *pgdb}
    - { python: 3.7, env: [*djangomaster, *mysql], <<: *mariadb}
    - { python: 3.7, env: [*djangomaster, *sqlite]}

    - { python: 3.8, env: [*django22, *postgres], <<: *pgdb}
    - { python: 3.8, env: [*django22, *mysql], <<: *mariadb}
    - { python: 3.8, env: [*django22, *sqlite]}
    - { python: 3.8, env: [*django30, *postgres], <<: *pgdb}
    - { python: 3.8, env: [*django30, *mysql], <<: *mariadb}
    - { python: 3.8, env: [*django30, *sqlite]}
    - { python: 3.8, env: [*django31, *postgres], <<: *pgdb}
    - { python: 3.8, env: [*django31, *mysql], <<: *mariadb}
    - { python: 3.8, env: [*django31, *sqlite]}
    - { python: 3.8, env: [*djangomaster, *postgres], <<: *pgdb}
    - { python: 3.8, env: [*djangomaster, *mysql], <<: *mariadb}
    - { python: 3.8, env: [*djangomaster, *sqlite]}

  allow_failures:
    - env: [*djangomaster, *postgres]
    - env: [*djangomaster, *mysql]
    - env: [*djangomaster, *sqlite]


install:
  - pip install -r test-requirements.txt
  - bash -c "if [[ $DATABASE_URL = postgres* ]] && [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then pip install psycopg2cffi; fi;"
  - bash -c "if [[ $DATABASE_URL = postgres* ]] && [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install psycopg2-binary; fi;"
  - bash -c "if [[ $DATABASE_URL = mysql* ]]; then pip install mysqlclient; fi; "
  - bash -c "if [[ $DJANGO_VERSION = master ]]; then pip install https://github.com/django/django/archive/master.zip; else pip install "django==$DJANGO_VERSION"; fi;"
  - pip install -e .
script:
  - django-admin test
